Add missing throw/return methods to internal cancelable generator.
Otherwise regenerator can throw with errors like:
TypeError: The iterator does not provide a 'throw' method.
TypeError: The iterator does not provide a 'return' method.